# ```Numpy ```

### ```Numpy``` is a third party library for analyzing the data.

In [ ]:
import numpy as np # alias means nickname
a=np.array([1,2,3])# 1-d array means elements in a single row
a

array([1, 2, 3])

In [12]:
lst=[1,2,3,4]
arr=np.array(lst) # convert list to array
type(arr),arr

(numpy.ndarray, array([1, 2, 3, 4]))

In [16]:
a=np.arange(1,10)#using range function to print numbers from 1 to 9
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a=np.array([1, 2, 3])
b=np.array([1,2,3])
a+b

array([2, 4, 6])

In [ ]:
l=np.ones(1)#1-d array
print(l)
a=np.ones([2,2])#2-d array
print(a)
b=np.zeros(2)
print(b)
c=np.zeros([3,3])
c

[1.]
[[1. 1.]
 [1. 1.]]
[0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [34]:
h=np.linspace(1,10,5) #1 to 10 with 5 equally spaced numbers
h

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
num=np.arange(1,31).reshape(5,6) # 5 rows and 6 columns means 5x6 matrix here it converts a 1-d array to a 2-d array with specified shape
num

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [42]:
# to get random integers in a specified range
arr=np.random.randint(1,10,5) # 5 random integers between 1 and 10
arr
arr1=np.random.random(10)# 10 random floats between 0 and 1
arr1

array([0.25204004, 0.43203296, 0.81103085, 0.82820249, 0.29091125,
       0.95254679, 0.91629361, 0.78190081, 0.51147084, 0.82507802])

In [55]:
arr=np.arange(1,61).reshape(5,12)
arr
print((arr.shape),(arr.dtype))#data type
arr.size # total number of elements in the array
arr.ndim #dimension of array

(5, 12) int64


2

In [ ]:
g=np.arange(1,11).reshape(5,2) # 5 rows and 2 columns
h=g.ravel()
h
g=np.arange(1,11).reshape(5,2).ravel()#converting 2-d into 1-d
g
i=np.arange(1,11).reshape(5,2).flatten() # flattening the array(1-d array)
i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
#transpose of an array
arr=np.arange(1,11).reshape(5,2)
a=arr.T.shape
a


(2, 5)

In [ ]:
# indexing and slicing
arr=np.arange(1,11)
print(arr[0])# indexing element
print(arr[1:5])# slicing from index 1 to 4
print(arr[1:5:2])# slicing from index 1 to 4 with step size of 2
arr[3]=10 # changing the value at index 3
print(arr) # modified array after changing the value at index 3

1
[2 3 4 5]
[2 4]
[ 1  2  3 10  5  6  7  8  9 10]


In [77]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0,2]) # accessing element at row 0, column 2
print(arr[1:3, 0:3]) # slicing rows 1 to 2 and columns 0 to 2
print(arr[0:2, 0:2]) # slicing rows 0 to 1 and columns 0 to 1
print(arr[0:2, 0:2].shape) # shape of the sliced array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
(2, 2)


In [84]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1]) # accessing element at row 0, column 1
print(arr.dtype)

2
int64


In [86]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[::-1]) # reversing the array
print(arr[:, ::-1]) # reversing the columns of the array
print(arr[::-1,:]) # reversing the rows of the array

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [87]:
# 3-d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# creating a 3-d array with specific shape
arr=np.arange(40).reshape(2,5,4)# 3-d array with 2 layers, 5 rows, and 4 columns
print(arr.shape) # shape of the 3-d array
print(arr)

(2, 5, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]


In [95]:
# creating a 3-d array with random integers
arr=np.random.randint(1,10, size=(2,3,4)) # 2 layers, 3 rows, and 4 columns with random integers between 1 and 10
print(arr)
# creating a 3-d array with random floats
arr=np.random.random((2,3,4)) # 2 layers, 3 rows, and 4 columns with random floats between 0 and 1
print(arr)

[[[4 8 2 5]
  [1 6 3 5]
  [2 1 5 3]]

 [[6 4 8 8]
  [8 5 3 8]
  [2 3 2 9]]]
[[[0.6560863  0.87270355 0.14532274 0.64601909]
  [0.47766393 0.34051378 0.71446095 0.65784399]
  [0.69809073 0.95363514 0.61634331 0.96889818]]

 [[0.94002953 0.31161517 0.03851326 0.53161947]
  [0.8138716  0.48032216 0.18272815 0.53853124]
  [0.44999382 0.87098645 0.77397422 0.76205577]]]


In [100]:
# slicing in the 3-d array
arr=np.arange(1,25).reshape(2,3,4) # creating a 3-d array with shape (2, 3, 4)
print(arr)
print(arr[0, 1, 2]) # accessing element at layer 0, row 1, column 2
print(arr[0, 1:4, 1:5]) # accessing all elements in layer 0


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
7
[[ 6  7  8]
 [10 11 12]]


In [109]:
# common operations on arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])  
print(arr1+2)  # adding 2 to each element
print(arr1 * 3)  # multiplying each element by 3
print(arr1 + arr2)  # element-wise addition
print(arr1 - arr2)  # element-wise subtraction
print(arr1 * arr2)  # element-wise multiplication
print(arr1 / arr2)  # element-wise division
print(arr1 ** 2)    # element-wise exponentiation
print(np.mean(arr1))  # mean of the array
print(np.median(arr1))  # median of the array   
print(np.std(arr1))  # standard deviation of the array
print(np.var(arr1))  # variance of the array
arr3=np.array([2,3,5,6,4,8])
arr3.argsort()# returns the indices that would sort the array




[3 4 5]
[3 6 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
2.0
2.0
0.816496580927726
0.6666666666666666


array([0, 1, 4, 2, 3, 5])